### ISSUE TITLE
Any way to ignore a directory? 

### ISSUE THREAD

**Issue by nwhobart** [Makeshift/generate-dependabot-glob-action#25]
First off thanks for this workflow. Really appreciate it. I have a folder structure that looks similar to:

```
➜ ls
README.md modules   test1     test2     test3
```

is there any way to transform this so i can ignore the `modules` directory entirely?:

```
- package-ecosystem: 'terraform'
  directory: '*/\.terraform.lock.hcl'
  commit-message:
    prefix: 'terraform'
  schedule:
    interval: 'weekly'
```

I have tried following a pattern as given in the [glob docs](https://www.npmjs.com/package/glob?activeTab=readme) 

```
// all js files, but don't look in node_modules
const jsfiles = await glob('**/*.js', { ignore: 'node_modules/**' })
```

However I get errors on the run: 

```
YAMLException: bad indentation of a mapping entry (11:51)


 11 |  ... erraform.lock.hcl, { ignore: 'modules/**' }'
-----------------------------------------^
 12 |  ... 
 13 |  ... rm'
    at generateError (/runner/_work/_actions/Makeshift/generate-dependabot-glob-action/master/dist/index.js:6344:10)
    at throwError (/runner/_work/_actions/Makeshift/generate-dependabot-glob-action/master/dist/index.js:6348:9)
    at readBlockMapping (/runner/_work/_actions/Makeshift/generate-dependabot-glob-action/master/dist/index.js:7343:7)
    at composeNode (/runner/_work/_actions/Makeshift/generate-dependabot-glob-action/master/dist/index.js:7602:12)
    at readBlockSequence (/runner/_work/_actions/Makeshift/generate-dependabot-glob-action/master/dist/index.js:7169:5)
    at composeNode (/runner/_work/_actions/Makeshift/generate-dependabot-glob-action/master/dist/index.js:7633:45)
    at readBlockMapping (/runner/_work/_actions/Makeshift/generate-dependabot-glob-action/master/dist/index.js:7325:11)
    at composeNode (/runner/_work/_actions/Makeshift/generate-dependabot-glob-action/master/dist/index.js:7602:12)
    at readDocument (/runner/_work/_actions/Makeshift/generate-dependabot-glob-action/master/dist/index.js:7786:3)
    at loadDocuments (/runner/_work/_actions/Makeshift/generate-dependabot-glob-action/master/dist/index.js:7849:5) {
  reason: 'bad indentation of a mapping entry',
  mark: {
    name: null,
    buffer: 'version: 2\n' +
      '\n' +
      'updates:\n' +
      "- package-ecosystem: 'github-actions'\n" +
      '  # No globs\n' +
      "  directory: '/'\n" +
      '  schedule:\n' +
      "    interval: 'daily'\n" +
      '\n' +
      "- package-ecosystem: 'terraform'\n" +
      "  directory: '**/\\.terraform.lock.hcl, { ignore: 'modules/**' }'\n" +
      '  commit-message:\n' +
      "    prefix: 'terraform'\n" +
      '  schedule:\n' +
      "    interval: 'weekly'\n",
    position: 207,
    line: 10,
    column: 50,
    snippet: "  8 |  ... '\n" +
      '  9 |  ... \n' +
      " 10 |  ...  'terraform'\n" +
      " 11 |  ... erraform.lock.hcl, { ignore: 'modules/**' }'\n" +
      '-----------------------------------------^\n' +
      ' 12 |  ... \n' +
      " 13 |  ... rm'"
  }
}
Error: bad indentation of a mapping entry (11:51)
```
 
 Any thoughts on if what I'm trying to do is possible?

**Comment by Makeshift** [comment]
~~In the background, the workflow uses [glob](https://www.npmjs.com/package/glob), which a quick glance at the docs suggests it isn't possible to provide ignores in the search string.~~

Whoops, didn't see the part of your issue where you'd already found that! 

I'm unfortunately not at my computer right now, but I may be able to have a look at trying to support this in a few days. 

I'm reluctant to modify the format of the input template or add more keys to it, so to avoid confusion it might be possible to have a json file in the dir with additional options to pass to glob.

Alternatively, I could maybe have it obey the ignore rules specified in the yaml that dependabot uses (if I remember correctly it can define ignores, right? It's been a little while!) 

What are your thoughts on the best option?

**Comment by nwhobart** [comment]
isn't `ignore` a globOption? 

`ignore` string or string[], or an object with ignore and ignoreChildren methods.

Are you saying you don't want to do something like this: 

```
const ignorePattern = core.getInput('ignore-pattern');

const globOpts = {
  root: process.cwd(),
  mark: true,
  matchBase: true,
  nomount: true,
  follow: actionOpts['follow-symbolic-links'],
  ...(ignorePattern && { ignore: ignorePattern })
}
```

I know enough js to get myself in trouble so this may be way off base. 

> I'm reluctant to modify the format of the input template or add more keys to it, so to avoid confusion it might be possible to have a json file in the dir with additional options to pass to glob.  Alternatively, I could maybe have it obey the ignore rules specified in the yaml that dependabot uses (if I remember correctly it can define ignores, right? It's been a little while!)

Passing additional options via a json isn't a huge deal but it would be more rad if it could be done using a `with:` but I can see how you'd want to avoid confusion. 

As far as the `ignore` from dependabot it [definitely exists](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore) but does not include ignoring directories.
